### ISSUE TITLE
Dependency loop between vsgGIS and vsxXchange

### ISSUE THREAD

**Issue by saedrna** [vsg-dev/vsgGIS#2]
vsgGIS has 

https://github.com/vsg-dev/vsgGIS/blob/120f79b46f3619acc438b64329ddba04758ae6f2/CMakeLists.txt#L73-L78

And vsxXchange has

https://github.com/vsg-dev/vsgXchange/blob/a4deab3fffb98b018aec1b19276319c5cad5914e/src/gdal/build_vars.cmake#L2

Although they are `find_package(xxx QUIET)`, it is clearly a dependency loop.

**Comment by robertosfield** [comment]
Thanks for spotting the error.  This is is a hang over over when vsgGIS did indeed depend upon vsgXchange, the relationship has since changed but I obviously missed removing this find_package(..) entry.  I have remove the offending lines and checked it into vsgGIS master.

    [#58777a447bbca6c07c3c9d432a297f594ddacec9](https://github.com/vsg-dev/vsgGIS/commit/58777a447bbca6c07c3c9d432a297f594ddacec9)
